### test Login
POST http://localhost/signIn
Connection: keep-alive
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
sec-ch-ua-platform: "Linux"
Accept: */*
Origin: http://localhost
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost/sign-in
Accept-Language: en-DE,en;q=0.9,cs-CZ;q=0.8,cs;q=0.7,ru-RU;q=0.6,ru;q=0.5,en-GB;q=0.4,en-US;q=0.3
Cookie: Phpstorm-d3bf0507=9ad817ae-dcce-4850-96cd-186b9114ecce; adminId=null; sessionId=null
Content-Type: application/json

{
  "email": "alvina@gmail.com",
  "password": "640afa65be5bfacffe4bc2e7516c1096"
}

> {%
   client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is 200");
    });
   client.global.set("sessionId", response.body.sessionId);
 %}

### order test notEmpty sessionId

POST http://localhost/order
Connection: keep-alive
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
sec-ch-ua-platform: "Linux"
Accept: */*
Origin: http://localhost
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost/order
Accept-Language: en-DE,en;q=0.9,cs-CZ;q=0.8,cs;q=0.7,ru-RU;q=0.6,ru;q=0.5,en-GB;q=0.4,en-US;q=0.3
Cookie: Phpstorm-d3bf0507=9ad817ae-dcce-4850-96cd-186b9114ecce; sessionId={{sessionId}}; adminId=null
Content-Type: application/json

{
  "sessionId": "{{sessionId}}",
  "delivery": "Take Away",
  "payment": "PayPal",
  "cart": {
    "2": 1,
    "3": 1
  },
  "shipping": {
    "firstName": "Alvina",
    "lastName": "Lushnikova",
    "postalCod": "19000",
    "address": "Praha",
    "city": "Peslova, 94/6",
    "number": "+420773502852",
    "info": ""
  }
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is 200");
    });

 %}

